GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMwLCJuYW1lIjoiWWF6aWQiLCJlbWFpbCI6ImdoYW5pQGdtYWlsLmNvbSIsImlhdCI6MTcwMjk3MzI2NCwiZXhwIjoxNzAyOTczMzI0fQ.2M8k7o2jLejeVOePhqMtO8eIvz8vKzDVO3ZZLJ1F_-k
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name" : "Yazid",
    "email" : "ghani@gmail.com",
    "password" : "abcdef",
    "confPassword" : "abcdef"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "ghani@gmail.com",
    "password" : "abcdef"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout
